######################################################################
# Automatically generated by qmake (2.01a) Tue May 17 21:40:48 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
QT += webkit
HEADERS += pobierz_dane.h
FORMS += pobierz_dane.ui
SOURCES += main.cpp pobierz_dane.cpp
